### ISSUE TITLE
Skosify Hochschulkompass classification

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-ssg#1]
See https://www.hochschulkompass.de/studium/studiengangsuche/erweiterte-studiengangsuche.html

There are three classifications:

1. by subject group ("Fächergruppe")
2. by study area ("Studienbereiche")
3. by field of study  ("Studienfelder")

We will have to find out which of those best to skosify.

**Comment by acka47** [comment]
As the fields in 3.) are grouped into subject groups in 1.) I propose to usethose for the SKOS file and create concepts out of 3.) which are put into `skos:Collection`s derived from 1.).

**Comment by acka47** [comment]
There are:

- 10 Fächergruppen (1.)
- 82 Studienbereiche (2.)
- 522 Studienfelder (3.)

So, I think we should go with the approach I already proposed:
> create concepts out of 3.) which are put into skos:Collections derived from 1.).

**Comment by literarymachine** [comment]
> create concepts out of 3.) which are put into skos:Collections derived from 1.).

@acka47 what about 2.?

**Comment by acka47** [comment]
We might as well create collections out of these. I hesitated to add more complexity but if we have collections in the first place it probably does not matter to add some more.

**Comment by literarymachine** [comment]
Ok. But does the `skos:Collection` approach mean that there won't be any `skos:ConceptScheme`?

**Comment by acka47** [comment]
>  But does the `skos:Collection` approach mean that there won't be any `skos:ConceptScheme`?

O. My thinking was strange. We probably are just dealing with a three-level hierarchy (although the UI of the Hochschulkompass does not make it that clear), with Fächergruppen a top-level concepts, then Studienbereiche on second level and Studienfelder at the bottom. So we should represent this in SKOS accordingly.  Here is an example:

```
@prefix : <namespace#> .

<scheme>  a skos:ConceptScheme ;
  dct:title "Klassifikation des Hochschulkompass" ;
  skos:hasTopConcept :F1, :F17, :F56, :F146, :F381, :F193, :F255, :F382, :F273, :F380 .

:F273 a skos:Concept ;
   skos:prefLabel "Sprach- und Kulturwissenschaften"@de ;
   skos:inScheme <scheme> .

:B320 a skos:Concept ;
   skos:prefLabel "Kulturwissenschaften" ;
  skos:inScheme <scheme> ;
   skos:broader :F273 .

:S322 a skos:Concept ;
   skos:prefLabel "Kultur und Technik" ;
  skos:inScheme <scheme> ;
   skos:broader :B320 .
```

**Comment by acka47** [comment]
BTW, taking a deeper look at the page, I also found a description of the classification at https://www.hochschulkompass.de/studienbereiche-kennenlernen.html:

> Alle Studienmöglichkeiten im Hochschulkompass sind einem oder mehreren Studienfeldern zugeordnet. Ein Studienfeld umfasst einen Teilbereich eines Wissens- oder Themengebiets, unter dem ähnliche Studiengänge zusammengefasst sind. Mehrere Studienfelder gehören wiederum zu einem bestimmten Studienbereich und mehrere Studienbereiche zu einer Fächergruppe. Das bedeutet, dass alle Studienmöglichkeiten im Hochschulkompass nach Wissens- und Themengebieten gegliedert sind, so dass die Studiengangsuche auch thematisch und schrittweise von den übergeordneten Fächergruppen über die Studienbereiche und Studienfelder bis hin zu den Studiengängen konkretisiert werden kann.

**Comment by acka47** [comment]
Going forward with the vocab, we might add some documentation properties (`scopeNote` etc.) with content from the description pages under https://www.hochschulkompass.de/studienbereiche-kennenlernen.html, e.g. https://www.hochschulkompass.de/kunst-musik-und-design.html for F146.

**Comment by acka47** [comment]
We agreed to adjust the namespace (not use "Hochschulkompass") and to configure the redirect with w3id. Will do that this week.

**Comment by acka47** [comment]
Closing this, as the respective PR is already merged. Opened #13 & #14 for the next tasks.
