### ISSUE TITLE
Configure W3ID for example vocab

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-ssg#14]
From https://github.com/hbz/skohub-ssg/issues/1#issuecomment-514550237:

> We agreed to adjust the namespace (not use "Hochschulkompass") and to configure the redirect with w3id.

**Comment by acka47** [comment]
Should I use `http://test.skohub.io/w3id.org/class/hochschulfaecher` for the redirect or can I already use the production URL ( `http://skohub.io/w3id.org/class/hochschulfaecher`)? In the second case we should probably configure the webserver to redirect to `test` until we have the system ready for production...

**Comment by literarymachine** [comment]
Please use http://test.skohub.io/w3id.org/class/hochschulfaecher for now.

**Comment by acka47** [comment]
Ok, I added it to the hbz/w3id.org, see https://github.com/hbz/w3id.org/commit/754ac10b20a31ffc07caaee3ad5587b2e8df8ba5. Please take a look at it @literarymachine when the updated vocab is published. (I used to put a lot of mistakes into .htaccess config...) I will then open a PR at  perma-id/w3id.org.

**Comment by acka47** [comment]
https://github.com/perma-id/w3id.org/pull/1451 is merged and redirects are working, see e.g. http://w3id.org/class/hochschulfaecher/scheme. Closing.
