### ISSUE TITLE
Support collapsing and expanding tree view

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-ssg#27]
As a user I want to be able to collapse and expand the whole schema as well as parts of it in order to easily get an overview over a classification.

**Comment by literarymachine** [comment]
When using the search box, should the whole be searched, i.e. implicitly expanded?

**Comment by acka47** [comment]
> When using the search box, should the whole be searched, i.e. implicitly expanded?

Yes, I think so. I am quite happy with this UI/UX: https://nwbib.de/spatial

**Comment by literarymachine** [comment]
> Maybe we should even also collapse as default...

+1

**Comment by literarymachine** [comment]
On test, see e.g. https://test.skohub.io/literarymachine/skos/w3id.org/class/hochschulfaecher/scheme.html

**Comment by acka47** [comment]
> As a user I want to be able to collapse and expand the whole schema as well as parts of

The second part works (collapsing/expanding parts of the schema) but the first part not yet as there is no button to expand/collapse the whole schema. Please add a "expand all"/collapse all" button.

**Comment by acka47** [comment]
However, as it is already a huge improvement over the status quo, you might as well deploy it now and add the buttons later.
