### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by dr0i** [hbz/skohub-ssg#31]
Don't know if this is actually of importance - however, every time i do `$ npm i` it's warning
> found 16160 vulnerabilities (16156 high, 4 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

My npm version is:
> $ npm --version
6.9.0

When I do the `audit fix`, some packages are downgraded like e.g.:

> "convert-source-map": "1.6.0" => "convert-source-map": "^1.1.0",

Even so, things seems to be builded and running just fine.

Also, my `npm` prefixes the version numbers of the packages with an `^` , I think to be even more on the sure side that the version number will be the correct one.

You may reject this PR, just in case, to let you know, for what it's worth.

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/skohub-ssg/pull/32
