### ISSUE TITLE
Add link to BARTOC entry

### ISSUE THREAD

**Issue by nichtich** [hbz/skohub-ssg#7]
We created a record for the classification in BARTOC: https://bartoc.org/en/node/18914 Once the classification is available in SKOS, the URL should also be added to BARTOC.

**Comment by acka47** [comment]
Hello @nichtich, we now have a stable URI for the vocabulary: http://w3id.org/class/hochschulfaecher/scheme#

As I can not edit BARTOC, would you please add it and also adjust the name of the classification?

**Comment by acka47** [comment]
I added the link but it is not shown in the HTML view, see https://bartoc.org/en/node/18914. Closing.
